tests/selenium_tests/openhrm_test.py::OpenHRMTest::test_add_user
--------------------------------------------------------------------
Last Page: data:,
 Duration: 0.53s
  Browser: Chrome 120.0.6099.109
   Driver: chromedriver 120.0.6099.71
Timestamp: 1702699201  (Unix Timestamp)
     Date: Friday, December 15, 2023
     Time: 10:00:01 PM  (Central Daylight Time, UTC-05:00)
--------------------------------------------------------------------
Traceback:
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\tests\selenium_tests\openhrm_test.py", line 17, in test_add_user
    allure.attach(self.save_screenshot_after_test)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\allure_commons\_allure.py", line 200, in __call__
    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\allure_pytest\listener.py", line 249, in attach_data
    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\allure_commons\reporter.py", line 165, in attach_data
    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bughr\PycharmProjects\SeleniumPython\seleniumvenv\Lib\site-packages\allure_commons\logger.py", line 53, in report_attached_data
    attached_file.write(body)
Exception: a bytes-like object is required, not 'bool'